### PR TITLE
Use nan 1.9 for ErrnoException and FatalException

### PR DESCRIPTION
**Pull request by sam-github**
Depends on https://github.com/nodejs/nan/pull/372 - it can't land until that is accepted, and nan 1.9 is released.

### CODE REVIEW

**Comment by sam-github** [comment]
@baudehlo https://github.com/nodejs/nan/blob/v1.9.0/CHANGELOG.md#190-jul-31-2015

This is mergeable now.

**Comment by sam-github** [comment]
@baudehlo ping!

**Comment by baudehlo** [comment]
Merged. Sorry about the delay. I'll push a new version to npm.

**Comment by sam-github** [comment]
thank you

**Pull request merged**
