### PR TITLE
Update nan dependency

### PR DESCRIPTION
**Pull request by davedoesdev**
So npm doesn't fall back to pre 2.1.0 if other projects want that.

### CODE REVIEW

**Comment by davedoesdev** [comment]
@baudehlo done

**Comment by davedoesdev** [comment]
I updated `package-lock.json` too.

**Comment by baudehlo** [comment]
npm publish
+ fs-ext@1.2.1

(Thanks!)

**Comment by davedoesdev** [comment]
Thanks for publishing

**Pull request merged**
