### PR TITLE
Add support for file locking via fcntl. Flock doesn't work well with NFS...

### PR DESCRIPTION
**Pull request by TomMettam**
Self explanatory, really :)

We wanted to lock files via NFS, and unfortunately flock() doesn't do this correctly.

This adds support for file locking functionality via fcntl.

### CODE REVIEW

**Comment by TomMettam** [comment]
Merged latest changes from upstream. @baudehlo  - any chance you could look at this?

**Comment by baudehlo** [comment]
Looks good to me. Is there any way to add tests for this or does it require an NFS drive available?

**Comment by TomMettam** [comment]
@baudehlo - It works on a regular filesystem too, so tests can be written to check the calls themselves.. Testing if it actually works, though might be more tricky - you'd need to fork a concurrent thread in order to test that the locking is actually working.

**Comment by dignifiedquire** [comment]
@baudehlo any chance of this getting merged? This is exactly what I need would love to see this merge.d

**Comment by baudehlo** [comment]
Can you pull this up to date with the new master? That way the travis tests will run. Thanks.

**Comment by TomMettam** [comment]
Done.

**Comment by baudehlo** [comment]
Merged. I'll try and cut a 0.7.0 release asap.

**Pull request merged**
