### PR TITLE
Use Nan v2

### PR DESCRIPTION
**Pull request by ggreer**
This PR updates fs-ext to work with Nan v2. This is needed for compatibility with io.js v3 and the soon-to-be-released node.js v4. Tests pass on OS X 10.10.5, using io.js v3.2.0. Sorry for the huge number of changes, but Nan v2's API is quite different from v1.

If you prefer, I can squash these commits. I'm never sure if maintainers like clean commits or if they want more insight into how the code was made.

### CODE REVIEW

**Comment by baudehlo** [comment]
How far back does the backcompat of Nan2 go?

**Comment by ggreer** [comment]
The Nan README says it works with versions as old as Node v0.8, but I haven't tested it. Maybe some Travis CI tests would be a good idea? I can submit a PR for that, but someone with push access would have to enable the hooks.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by pmurias** [comment]
why will this need to be undone for V8 4.7?

**Comment by baudehlo** [comment]
Since there's no answer to this question, I'm just going to merge and release this.

**Comment by ggreer** [comment]
Thanks. Can you please tag a new release?

**Pull request merged**
