### PR TITLE
Fix deprecation warnings on Node 10

### PR DESCRIPTION
**Pull request by davedoesdev**

### CODE REVIEW

**Comment by davedoesdev** [comment]
Thanks for merging. Could you publish a new version please?

**Comment by baudehlo** [comment]
```
$ npm publish
+ fs-ext@1.1.0
```

**Comment by davedoesdev** [comment]
@baudehlo thanks!
Although the tests pass, I'm seeing an issue with a project that's using the new version. I'll investigate further...

**Comment by davedoesdev** [comment]
#73

**Pull request merged**
